import { OnChanges, OnInit } from '@angular/core';
import { FormControl, FormGroup, NgControl, ControlValueAccessor } from '@angular/forms';
import { PartialEntity } from '../../models/entity';
import { EntityService } from '../../services/entity.service';
import { LogService } from '../../services/log.service';
export declare class EntitySelectorComponent implements ControlValueAccessor, OnInit, OnChanges {
    ngControl: NgControl;
    private entityService;
    private logService;
    label: string;
    name: string;
    id: string;
    onChange: Function;
    onTouched: Function;
    entitySelectionFormGroup: FormGroup;
    inputCtrl: FormControl;
    optionsCtrl: FormControl;
    entities: PartialEntity[];
    hasFocus: boolean;
    incomingEntity: PartialEntity;
    selectedEntity: PartialEntity;
    isSearching: boolean;
    writeValue(value: any): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    constructor(ngControl: NgControl, entityService: EntityService, logService: LogService);
    createForm(): void;
    ngOnInit(): void;
    ngOnChanges(): void;
    displayEntityAs(entity?: PartialEntity): string | undefined;
    onFocus(event: any): void;
    onBlur(event: any): void;
    onSelected(event: any): void;
    onMouseDown(): void;
    getTitle(entity: PartialEntity): string;
    formatResults(entity: PartialEntity, searchTerm: string): string;
}
